<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>tCC tN Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>1</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9f59f8b5-7e06-41d3-b498-6e2b12937829</testSuiteGuid>
   <testCaseLink>
      <guid>5937b058-da00-44c3-af8e-0c5b9c55223a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tCC Test Cases/tCC tN Test Edit Outline</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef8b6517-cdf9-4c2c-a030-dfec5f35bc8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fd23532-cd40-400f-aaca-937c0215f727</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da4c0e12-2bef-41d8-99e7-474f09b7dc95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f6cc8a7-7b1a-46de-b073-9af6cf4a5595</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0025cda-f8dd-4601-933f-acec361ec2e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tCC Test Cases/tCC tN Test Edit OrigLangQuote</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20112659-c480-4e0e-b0b2-1d5c6eeb86cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f4cdb0a-abd8-4562-a692-3e1cbe072e47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4632d25e-be73-45bd-9452-682d31c8525a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16d4792d-e72b-4aa3-bc7e-b88bdc128993</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17d393b2-76f9-4d5f-8e39-e59bd9c2cd9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tCC Test Cases/tCC tN Test Column Options</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79712a2d-b44b-47a0-9923-c4eafe51d1da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>466eab59-2b1e-47a5-b0f7-59094c19231f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf8d647b-8aaa-43e9-ad17-9d0601c46fc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14c7088a-024c-4738-a470-7c32d05bab93</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
