<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>tCC Test Suite 1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>13a68aee-9492-4797-b16b-0f9b864e0be2</testSuiteGuid>
   <testCaseLink>
      <guid>04d94791-a73b-4c50-8886-8fb4a7f3508a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tCC Test Cases/tCC tN Test Column Options</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79712a2d-b44b-47a0-9923-c4eafe51d1da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>466eab59-2b1e-47a5-b0f7-59094c19231f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf8d647b-8aaa-43e9-ad17-9d0601c46fc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14c7088a-024c-4738-a470-7c32d05bab93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf6facb6-c5b2-44ec-b29a-1d15ae1690d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tCC Test Cases/tCC tN Test Copy OrigLangQuote</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d0c32f8-0550-4a75-b7db-84086d7767ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff73824d-af4f-49f1-8e25-500338a480b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b8f6404-88f9-4c8c-95bc-ac985ac78e22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f704233f-fe61-4469-9d07-814f909261de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31b8d6d8-dcad-4e81-8291-7e5550602519</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tCC Test Cases/tCC tN Test Edit OrigLangQuote</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20112659-c480-4e0e-b0b2-1d5c6eeb86cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f4cdb0a-abd8-4562-a692-3e1cbe072e47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4632d25e-be73-45bd-9452-682d31c8525a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16d4792d-e72b-4aa3-bc7e-b88bdc128993</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f10648c-f64a-44f9-985f-6c5c08676da6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tCC Test Cases/tCC tN Test Edit Outline</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef8b6517-cdf9-4c2c-a030-dfec5f35bc8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fd23532-cd40-400f-aaca-937c0215f727</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da4c0e12-2bef-41d8-99e7-474f09b7dc95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f6cc8a7-7b1a-46de-b073-9af6cf4a5595</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2714ed1f-10f9-4b2d-912a-102fe1c71f99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tCC Test Cases/tCC tA Test Block Quotes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>539ade9c-551e-4b50-a35e-96cde2373dc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2efbe80c-5f49-421c-b1a7-cc6f145e31c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88ecf495-b837-4ae8-b4b9-9ee4c27943ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de66dbc3-c215-45a8-b7f6-41f3ca480d90</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>232f1a3d-1344-4eef-afad-d793502a351f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tCC Test Cases/tCC Test Permissions</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e83dae57-01d2-4991-a4b5-01afbf5517e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tCC Test Cases/tCC Test Multiple Sessions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e8f371b-ba65-434f-95ff-64102d8c3e11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d596a5f5-6fae-4e55-83b6-3716d4289d0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fda8670-c49e-4d26-91cc-b68c6cddc3ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23f11733-810b-4f73-8199-5bcd6e9ee0c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>769e85b5-2e0f-41b7-80e7-740e1c809cde</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
